### ISSUE TITLE
Auth overhaul

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#74]
Hi Aquib,

This will be for our next sprint :)

We need to revamp the way we handle user verification, password setting, and password resetting. We want to move user auth onto the website and off of the dashboard. When a user is created for a company in the dashboard, they see this when verifying their email and it's pretty confusing:

![image](https://user-images.githubusercontent.com/22153546/38860191-eb741052-422f-11e8-8a48-bb901122aaf7.png)

### Verification

- When an admin user creates a new company, they should receive the verification email as normal and land on the verify page (https://dashboard.rehive.com/#/verification) after registering. **This does not change.**
- The link in the verification email should change which page it directs users to. This should be a page in the static site called rehive.com/verification. Once a user clicks the link in the email, it should verify them and show this success page:

![image](https://user-images.githubusercontent.com/22153546/38875565-ebcbff6c-425a-11e8-8fd0-7bbec05d3d17.png)

The link "Admin dashboard log in" should be to https://dashboard.rehive.com/#/login

If the user verifying their email is an admin user, they should be logged in going to that link.
If the user verifying their email is a user added via the dashboard, but not an admin user, the link will be pointless for them. 

### Log in page

Please adjust the login page to add the following:

1. Rehive logo on the top left
2 Adjust the placement of the buttons to be the same distance from the top of the page as the Rehive logo, and the same distance to the left as the Rehive logo is to the right.
3. Change the heading from "Log in" to "Dashboard log in"

### Password set

Currently, when a user is added via the dashboard, they are sent an email to set their password. This just redirects them to the login page, and they cannot set their password.

We need a new page specifically for setting a user's password. It will also exist on the Rehive site rather than the dashboard. It uses the same api point as password reset, as they function the same way. https://api.rehive.com/3/auth/password/reset/confirm/ 

Password set page: 

![image](https://user-images.githubusercontent.com/22153546/38876966-e5140f90-425d-11e8-8b50-f04d94f0adf9.png)

When a user has successfully set their password:

![image](https://user-images.githubusercontent.com/22153546/38877033-17030074-425e-11e8-91df-61eb3fdeddbb.png)

### Password reset

The password reset email should only be used if a user requests a password reset email.

![image](https://user-images.githubusercontent.com/22153546/38877152-5843f9f8-425e-11e8-9b21-e9e2169b27f6.png)

![image](https://user-images.githubusercontent.com/22153546/38877172-6650e5c4-425e-11e8-9b61-eb952a0f8827.png)

### Dashboard admin

We need a way for admins to trigger the resending of 

1. verification emails
2. Password set emails
3. Password reset emails

Please add a block to the user's page on the dashboard under "User settings" called "Administration" and add 3 links:

Resend verification email
Resend password set email
Resend password reset email

The password ones use the same API end point as above.

![image](https://user-images.githubusercontent.com/22153546/38877559-3822501a-425f-11e8-89a5-dc7e37cf65c0.png)

**Comment by Cupofassam** [comment]
issue74 in dashboard repo
issue74d in website repo

**Comment by Cupofassam** [comment]
Looking good Aquib!

Some feedback:

1.When a user has no email address, the resend verification email box is empty:

![image](https://user-images.githubusercontent.com/22153546/39755331-ba8088a8-52c5-11e8-93d7-6dff6d793198.png)

Can you please add the following copy:

`No email address found for this user. Please <add an email address> before resending a verification email.`

where <add an email address> is alink that opens the add user email modal.

![image](https://user-images.githubusercontent.com/22153546/39755379-e6a72d6a-52c5-11e8-9d0f-f9bf9d8b437c.png)

2. For the Password set and password reset success pages, please move the copy higher up. It should be in the centre between the bottom of the heading and the bottom of the box:

![image](https://user-images.githubusercontent.com/22153546/39755495-5a217f66-52c6-11e8-8197-300663c91467.png)

3. In the resend verification email dropdown, please only show unverified email addresses. If there are no unverified email addresses, please show this copy:
`There are no unverified email addresses associated with this account.`

4. For resend/password set/resent link, please do a check on the user to see if if they have a primary email address associated with their user before doing the api call. If there is an email address but not a primary email address, show this text:
`Please set {email address} as the <primary email address>' - where <primary email address> will open the edit window for the found email address. 
If no email addresses are found at all please show this text:
`No email address found for this user. Please <add an email address> before resending a password link.` where <add an email address> is alink that opens the add user email modal.

5. When a user has no email address, if we add an email address for them in the dashboard, please force it to be primary.

**Comment by Cupofassam** [comment]
Thanks Aquib

If I have an invalid value on a password reset, it needs to have validation on the page itself - I shouldn't get an error on the next page with no obvious way to get back to the previous page:

![image](https://user-images.githubusercontent.com/22153546/39825241-9a04b7d8-53b1-11e8-96f6-816105f05bf9.png)

![image](https://user-images.githubusercontent.com/22153546/39825327-cd198194-53b1-11e8-886c-d3b798cc67b7.png)

Also the text still seems to be too low down, even when I check in incognito mode:

![image](https://user-images.githubusercontent.com/22153546/39825632-8bfe553a-53b2-11e8-82cc-074b87481368.png)

**Comment by AquiburRKhan** [comment]
Fixed it, but also try to hard reset if it persists

**Comment by Cupofassam** [comment]
Text is centered now :) as per slack pls rather display API validation errors on the fields themselves like we do with the contact form, back button is too clunky a flow.

**Comment by Cupofassam** [comment]
Working in general but I still get the `Invalid value` bug. I'm able to consistently recreate it now.

In Password set

1. In the "Password" field, enter your correct new password, e.g. pass5555
2. In the "Confirm password" field, enter half the password correctly e.g. pass
3. Get a "The two password fields didn't match" error.
4. Enter the correct password in the "Confirm password" field, e.g. pass5555. I did this just by adding 5555 to the end of my entered password - I did not erase the confirm password field and enter a totally new value.
5. Click "Set password". Nothing happens for a while, then I get the "Invalid value" error.

Side note, please change the error text for non-matching passwords. Let's make it `The two password fields don't match`

**Comment by Cupofassam** [comment]
Did some testing and it seems it first sends the response and I get a 200 status back, but nothing happens on the password set page i.e. it does not move to the "your password has been successfully set blah blah" page. So I click "set password" again, but the token is used up and therefore gives the "invalid value" error. So I think the problem is the success page is not being triggered correctly.

**Comment by Cupofassam** [comment]
👍 Merge it :)
